# Generated by Django 4.1.3 on 2023-12-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stixi_title', models.CharField(max_length=20, verbose_name='название стихотворения')),
                ('stixi_text', models.TextField(verbose_name='текст стихотворения')),
                ('pub_date', models.DateTimeField(verbose_name='год написания')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_comment', models.TextField(verbose_name='комментарии автора')),
                ('stixi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stixi.stixi')),
            ],
        ),
    ]
